### ISSUE TITLE
06 - SQL LCM set up.ps1 

### ISSUE THREAD

**Issue by ArieHein** [SQLDBAWithABeard/DSCV2#2]
Just remember that in your 04 pull server creation script, you went for no SSL, so in this script, the url needs to point to http, as in:

ServerURL = 'http://' + $PullServer + ':8080/PSDSCPullServer.svc'

**Comment by SQLDBAWithABeard** [comment]
@ArieHein I could kiss you!! 💯 . Thank you. Its the little things and sometimes you look at something for so long you don't see it.
